# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_resolved',
            field=models.BooleanField(default=True, verbose_name='Resolved?'),
        ),
    ]
